name: $(GITVERSION_SemVer)
trigger:
- release/*
- master

pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'

steps:

- task: NuGetToolInstaller@1
  displayName: 'Use NuGet'

- task: UseGitVersion@5
  displayName: GitVersion
  inputs:
    versionSpec: '5.x'
    updateAssemblyInfo: true

- task: NuGetCommand@2
  displayName: 'NuGet restore'

- task: VSBuild@1
  displayName: 'Build Solution'
  inputs:
    clean: true
    solution: '**\*.sln'
    configuration: 'release'
    msbuildArchitecture: 'x64'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'src/Abc123/*.csproj'
    packDirectory: 'artifacts'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'GITVERSION_NuGetVersion'
    configuration: 'release'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './artifacts'
    ArtifactName: 'drop'
    TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'


